services:
  drawio_export_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: production
    container_name: drawio-export-api
    ports:
      - "443:443"
    environment:
      PYTHONPATH: /app/src
    env_file: ./prod.env
    volumes:
      - ./nginx/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./nginx/certs/privkey.pem:/etc/nginx/certs/privkey.pem
