apiVersion: v1
kind: ConfigMap
metadata:
  name: drawio-export-api-supervisor-config
data:
  supervisord.conf: |
    [supervisord]
    nodaemon=true
    pidfile=/tmp/supervisord.pid
    logfile=/tmp/supervisord.log
    logfile_maxbytes=50MB
    logfile_backups=10
    loglevel=info

    [program:uvicorn]
    command=poetry run uvicorn drawio_export_api.main:app --uds /tmp/uvicorn.sock --workers 2
    autostart=true
    autorestart=true

    [program:nginx]
    command=/usr/sbin/nginx -g 'daemon off;'
    autostart=true
    autorestart=true
    user=appuser

    [supervisorctl]
